# Solve Ax = b using Jacobi Algorithm

Algorithm.

* Find D, the Diagonal of of A : _diag(A)_
* Find R, the Remainder of A - D : _A - diagflat(A)_

* Choose your initial guess, x[0]
    * Start iterating, k=0
        * While not converged do
           * Start your i-loop (for i = 1 to n)
               * sigma = 0
                * Start your j-loop (for j = 1 to n)
                   * If j not equal to i
                       * sigma = sigma + a[i][j] * x[j]k
                 * End j-loop
               * x[i]k = (b[i] – sigma)/a[i][i] : _x = (b - dot(R,x)) / D_
           * End i-loop
        * Check for convergence
    * Iterate k, ie. k = k+1


In [1]:
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot

def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
        print "x[", i,"]"
        pprint(x)
    return x

In [2]:
A = array([[2.0,1.0],[5.0,7.0]])
b = array([11.0,13.0])
guess = array([1.0,1.0])

sol = jacobi(A,b,N=25,x=guess)

print "A:"
pprint(A)

print "b:"
pprint(b)

print "x:"
pprint(sol)

x[ 0 ]
array([5.        , 1.14285714])
x[ 1 ]
array([ 4.92857143, -1.71428571])
x[ 2 ]
array([ 6.35714286, -1.66326531])
x[ 3 ]
array([ 6.33163265, -2.68367347])
x[ 4 ]
array([ 6.84183673, -2.6654519 ])
x[ 5 ]
array([ 6.83272595, -3.02988338])
x[ 6 ]
array([ 7.01494169, -3.02337568])
x[ 7 ]
array([ 7.01168784, -3.15352978])
x[ 8 ]
array([ 7.07676489, -3.1512056 ])
x[ 9 ]
array([ 7.0756028 , -3.19768921])
x[ 10 ]
array([ 7.0988446 , -3.19685914])
x[ 11 ]
array([ 7.09842957, -3.21346043])
x[ 12 ]
array([ 7.10673022, -3.21316398])
x[ 13 ]
array([ 7.10658199, -3.21909301])
x[ 14 ]
array([ 7.10954651, -3.21898714])
x[ 15 ]
array([ 7.10949357, -3.22110465])
x[ 16 ]
array([ 7.11055232, -3.22106683])
x[ 17 ]
array([ 7.11053342, -3.22182309])
x[ 18 ]
array([ 7.11091154, -3.22180958])
x[ 19 ]
array([ 7.11090479, -3.22207967])
x[ 20 ]
array([ 7.11103984, -3.22207485])
x[ 21 ]
array([ 7.11103743, -3.22217131])
x[ 22 ]
array([ 7.11108566, -3.22216959])
x[ 23 ]
array([ 7.11108479, -3.22220404])
x[ 2

In [3]:
sol.shape

(2,)